### ISSUE TITLE
Importing tab sessions overwrites (wipes) previous sessions saved

### ISSUE THREAD

**Issue by illustribe** [jaszhix/tab-master-5000-extension#14]
Hello,

I'm glad I just started to use your extension. Because otherwise I would've been VERY sad to loose all my saved tab sessions. Which I did, but they weren't many yet.

I basically had three sessions saved and then went on to import a JSON file from my other browser which had other sessions instead. The result was that I ended up ONLY with the newly imported sessions and my saved sessions were gone! :(

I hope you can find the problem and fix it since it could be VERY devastating to loose a lot of research time...

Thank you very much and good luck with your project! :D

**Comment by jaszhix** [comment]
Hi, sorry about this. I have a commit pushed to master that fixes this, and will publish soon after some testing.

**Comment by jaszhix** [comment]
Fixed in 2.9.1
