### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jeffslofish** [jaszhix/tab-master-5000-extension#15]
After doing a git clone and then running `yarn` I attempted to run `npm run build-chrome` per the contributing instructions and I get errors, beginning with:

```
[2] [19:50:56] Starting 'clean'...
[2] [19:50:56] The following tasks did not complete: clean
[2] [19:50:56] Did you forget to signal async completion?
[2] events.js:174
[2]       throw er; // Unhandled 'error' event
[2]       ^
[2] 
[2] Error: ENOENT: no such file or directory, open './dist/manifest.json'
```

I noticed that if I created the "dist" directory manually, then the error goes away and traced the problem to line 33 in webpack.config.js which is assuming that the ${WORKDIR} directory exists, which is "dist" in this case.

```
  .pipe(fs.createWriteStream(`./${WORKDIR}/manifest.json`));
```

It would be nice if the "dist" directory was automatically created if it doesn't exist, so that the first time you try to build it won't fail, since the "dist" directory is not included in the repo.

I could create a pull request to fix this if you like.

**Comment by jaszhix** [comment]
Hi, good catch. I can fix this, or you can PR. Either works. Thanks.

**Comment by jeffslofish** [comment]
Why don't you go ahead and fix it. I looked into it and there are a few different ways to do it and I wasn't sure which you would like the best.
