### ISSUE TITLE
Usability glitches

### ISSUE THREAD

**Issue by needleshaped** [jaszhix/tab-master-5000-extension#17]
1. While searching through tabs (Table Format only), when removing all search string, latest filtered list of tabs stays, but list of all tabs must be shown.
Test: open two different tabs, 1st contains letter "Z", 2nd - does not. Type "z", then backspace. Only 1 tab will be shown. Problem does not exist in Tile Format.

2. Similar - when switching between View Modes e.g. to Session, than back to Tabs - list does not change to tabs, unless SORT BY option is changed or Search is used.

3. Options page from Chrome Menu and Options from within extension in New Tab - are two different pages. Confusing.

**Comment by jaszhix** [comment]
Bugs 1 and 2 are fixed on master, and a new version has been submitted to the Chrome Web Store and Mozilla Addons sites. 

As for item 3, the options page just loads the Preferences component, so the whole New Tab page doesn't load when people just want to change the extension settings. The options can be accessed from either place - I don't understand what's confusing about it. Feel free to open a separate issue if you'd like to discuss it further.

**Comment by needleshaped** [comment]
No problem, thank you!
