### ISSUE TITLE
Tabmaster 5000 Not Working

### ISSUE THREAD

**Issue by ghost** [jaszhix/tab-master-5000-extension#21]
Tab Master 5000 isn't working, or I'm just unable to figure out how to get it to work.

**Comment by jaszhix** [comment]
Can you provide more info, such as browser and version, OS?

**Comment by ghost** [comment]
Windows 10 Home, Google Chrome is up to date... Version 80.0.3987.162
(Official Build) (64-bit).
If you don't mind, would you please direct me on how to use Tab Master
5000, as the issue is most likely merely my not knowing how to use it, &
being unable to find instructions anywhere.  Thank you very much for your
time & assistance, it is greatly appreciated.
[image: ThankYou6.png]

*Thomas BearMy Links <https://linktr.ee/otc_atheist>*

**Comment by jaszhix** [comment]
If you don't see it replacing the standard New Tab page in Chrome, you might need to manually set it to override the new tab in settings. Navigate to `chrome://settings`, if it doesn't say "Tab Master 5000 is controlling this setting" under "On Startup", you need to re-enable the extension in `chrome://extensions`.
