### ISSUE TITLE
Takes control of New Tab page

### ISSUE THREAD

**Issue by IMeanReallyNow** [jaszhix/tab-master-5000-extension#22]
Hi. 

Is there a way of disabling the extension from taking control of what happens when I open a new tab? 

I have Chrome set up to show me "apps" (chrome://apps/) and when TM5k is enabled, it shows me something else.  

Thank you. 
Be well. 
Nicole.

**Comment by jaszhix** [comment]
Hi, thanks for opening an issue. This is currently being tracked in #20.
