### ISSUE TITLE
Session saver

### ISSUE THREAD

**Issue by rayman89** [jaszhix/tab-master-5000-extension#5]
How does the session saver works? Does it have some automatic features or is it all manual (aka it only saves session when you press the button)? If it's all manual could you add features to save the session when closing firefox and/or every "x" amount of time?

**Comment by jaszhix** [comment]
Its automatic when you enable session synchronization in preferences, and then click the sync button next to a session in the session manager. I think this flow is too complicated though, and should be hassle-free.
