### ISSUE TITLE
Right click functions

### ISSUE THREAD

**Issue by rayman89** [jaszhix/tab-master-5000-extension#8]
Could you add on right click of the selected tabs the option to copy tab(s) url, reload tab(s), close tabs to the left/right and in case you implement to do things in bulk: select tabs from same domain and invert selection?

**Comment by jaszhix** [comment]
I have some of these features partially implemented in v2.6.0. I think there's a Web Extensions way to copy to the clipboard, I'll look into it next. At this rate though the extension needs a stockpile of permissions, so I'll probably try to use [execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#).

**Comment by jaszhix** [comment]
Added the copy to clipboard option to 2.7.0.
